### ISSUE TITLE
io.Copy(os.Stdout, p.StdOut()) coding exception

### ISSUE THREAD

**Issue by eaglebetter** [vladimirvivien/gexe#42]
When I run example "ping", Console display content coding exception，The statement executed is：io.Copy(os.Stdout, p.StdOut())，I used UTF-8 coding, but it didn't help. How to deal with text coding to make the console display normally？The exception display text is
���� Ping golang.org [142.250.199.81] ���� 32 �ֽڵ�����:
���� 142.250.199.81 �Ļظ�: �ֽ�=32 ʱ��=37ms TTL=52
���� 142.250.199.81 �Ļظ�: �ֽ�=32 ʱ��=26ms TTL=52

**Comment by vladimirvivien** [comment]
Hi. Apologies for the massive lateness.
How are you building and running the code?
What is your environment os, terminal setup, OS ?
I am not able to replicate on a terminal running OSX.
